#       #######                                                #
#    ###       ###                                             #
#   ##   ## ##   ##   F: build.yml                             #
#        ## ##                                                 #
#                     C: 2022/06/18 18:01:48 by:dnettoRaw      #
#   ##   ## ##   ##   U: 2022/06/19 14:10:11 by:dnettoRaw      #
#     ###########                                              #

name: Build

on: 
  push:
    branches:
      - release

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ self-hosted ] 
        # os: [windows-latest, ubuntu-latest, macOs-latest]

    env:
      RUST_VERSION: 1.61.0
      NODE_VERSION: 18.3
      GH_ACTIONS: true
      RUST_BACKTRACE: full

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ env.RUST_VERSION }}

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install webkit2gtk
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Build application
        run: |
          yarn
          yarn tauri build

      - name: Release App
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "TAURI Templaite Realesa v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          draft: true
          files: |
            src-tauri/target/release/bundle/dmg/myapp.dmg
            src-tauri/target/release/bundle/deb/myapp.deb
            src-tauri/target/release/bundle/msi/myapp.msi
      
      - name: echo
        run: |
          echo "${{matrix.NAME}} ${{ matrix.os }} ${{ matrix.kind }}  v__VERSION__  v__NAME__ ${{ steps.get_upload_url.outputs.url }} ${{ steps.version.outputs.version }} ${{ steps.get_latest_release.outputs.data }} " 
          echo "Build finished" 